#! /bin/bash
# /etc/init/

echo "                                                                                                           ,rlteekQQQB#QK."            
echo "                                                                                                        'z#@QQQ#8HqdQ@N9pwi"           
echo "                                                                                                     .LR@@@@@QRdQ@@#au#QAbe"           
echo "                                                                                                  *r6@@@@@@@Q@QDw8@QuijE#K%,"          
echo "                                                                                                .LRQ@@@@@@@@XyQ@@#SKc^^a4b4^"          
echo "                                                                                              ,jQ@@@@@@@@@@@QQQk#Bell7r^wpXc"          
echo "                                                                                            '6@@@@@@@@@@@@@@QQ@@Bav^lHBSjHpA*"         
echo "                                                                                          *sQ@@@@@@@@@@@@@@@@@@@@pvt6A%BoL8E,"         
echo "                                                                                         lQ@@@@@@@@@@@@@@@@@@@@@@@@QuvvJvvql^"         
echo "                                                                                       *4@@@@@@@@@@@@@@@@@@@@@@@@@@@dtl^lNw^l"         
echo "                                                                                     *rQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#lvpekz'"         
echo "                                                                                ***~^u@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@QHXkl"          
echo "                                                                        .iiirpQgDNQ@@Q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@QES*"          
echo "                                                                     lapDggQ@@@@@@@@N#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Bl"           
echo "                                                                  ijQ@@@@@@@@@@@@@@@N@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,"           
echo "                                                               */Q@@@@@@@@@@@@@@@@@@Q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@D"            
echo "                                                             ,o8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Q*"           
echo "                                                            'KQQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#"            
echo "                                                           lNQQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Qz"            
echo "                                                          LQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Qi"            
echo "                                                        *A@@Q@@@@@@@@@@@@@@@@@@@@@@@Q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@QyL"            
echo "                                                       ,6@QQ@##@@@@Q@@@@@@@@@@@@@@@@Q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Qolol"           
echo "                                                      uQQ@QQ@@@Rd%p@@@@@@@@@@@@@@@@@QD@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Q9Rj?ll."         
echo "                                                    .H@@@B#@QQQ@Wi7jQ@@@Q@@@@@@@@@@Q@Q6HQ@@@@@@@@@@@@@@@@@@@@@@@@@@@KB@#k7vJEl*"       
echo "                                                   '#@QA#@#bQ@QBDyXyjDQ@B@@@@@@@@@@E@@@QpwN@@@@@@@@@@@@@@@@@@@@@@QOK@@@QQjuAyuF*"      
echo "                                                  iQ##oe7iwQAjKWHdHg8XQ@@@@@@@@@@@@o@@@@@@##@@@@@@@@@@@@@@@@@@@@B#@@@QWWB#N#ziil"      
echo "                                                 /@@@QBNW%K%@QobbKdDQ@@@@@@@@@@@@@@w@@@@@@@@@@@@@@@@@@@@@@@@@QWB@@BeL/SSWQ@@#esj."     
echo "                                               'KQBQQQ#%HHdqH@N%O4e%#@@@@@@@@@@@@@@K@@@@@@@@@@@@@@@QQQ@@@Qg##@@@BylCDQOoa86FjWDW^"     
echo "                                              L@@QB##O9SEaeoHNQKaoXQ@@@@@@@@@@@@@@@R@@@@@8Q@@@@@@@@@@@@K#pQ@@@@gSDQ@@QDBEzK##8S/~"     
echo "                                            .d@@@@gHS%%jjXousoDHSaBQ@@@@@@@@@@@@@@@NQ@@@8g9pQ@@@@@@@@@@@K@@@@@@@@@@@@QpCwEwS7?lll"     
echo "                                           ,QQ@@BEEkauSRDXSljaSuidQ@@@@@@@@@@@@@@@@BQ@@QL/LoB@@@@@@@@@@6@@@@@@@@@@@@Qd6NK8g#QQ8Ai"     
echo "                                          'Q@BQ#juDjivCvLvC4uC*lQ@@@@Q@@@Q@@@@@@@@@dQ@@QjouQ@@@@@@Q@@Qk@@@@@@@@@@b@QQ@QH@Q#HD6KE"      
echo "                                          %@@@@@NCXBQ#H%BDONDbl%@@@@@@@@@@@@Q@@g4Apo9#@@@QQ@@@@@@@@@#p@@@@@@@@@@p@Q@Qgbu@BgA4oC*"      
echo "                                         ~@@@QdKOQ@@@RKp6au#8dwwNdQ@Q@@@@@@@@%suXka7ll7pHKDQ@@@@@@QpB@@@@@@@@@@@@@@Q#DwK@w78QQ^"       
echo "                                         i@@@@@@@@@QdSd8gQ%X#Qg4gJLeHNQ@@@@@@QWggqACllW#QKcqK@@@@gAQ@@@@@@@@@@@@@@@Q8pDo@6FuCC^"       
echo "                                         w@@@@@@@Q##bwFleecOQQQHHzr^l4ORN9@@@@@QQ@@QNzlQ@QaAzeQQHQ@@@@@@@@@@@@@@@@@@@Q%8@QKstzi"       
echo "                                         Q@@@@@@@@Qbsvil?*lgQQ@DlzilliDE6qoe4@@@@@@@We@dw@bpl*r7@@@@@@@@@@@@@@@@@@@@@QQQQ#gQQOi"       
echo "                                        v@@@@@@@B6yySjz7zCJQQ@Q8ol*?r?od9auK7jBQ@@@@QA@@Q#Qwv/v?jDQ@@@@@@@@@8@@@@@@@QQQEuu9wqwi"       
echo "                                      iK@@@@@@@@QQ##gKEaClJQ@@@@ucLl**lpEHBCCAej@@@@@@Q@@@QSdjLraQQoDg@@@@@Qo@@@@@Q#NNRFlCQQNb,"       
echo "                                    ~B@@@@@@@@@@@@QQQ##Q##@Q@@@Q7i//leo#Qgzaoz/^9%p@@@@@@@@9#gKpXQ@9Dwl4K#blD@@@@@#K944ulp#Q#p'"       
echo "                                  *C@@@@@@@@@@@@@@@@@@@@QQ@@@@@DzvvvzXQNdHbpEut4BQH@@@@@@@@QSQ@QQQ@@gKiiLS^FQ@@@@@@#w6RQ@@Q@Q8"       
echo "                                  l@@@@@@@@@@@@@@@@@@@@@@@@@@@BgNNQg%g8QQQNNDbQQQWQ@@@@@@@@@Ho@@@Q@@@#@DDpva8Q@Q@@@@@@@QBQQQQ%*"       
echo "                                  ?@@@@@@@@@@@@@@@@@@@@@@@@@QQ#Rd@@QoojWgWQ@@@QQQQ@QQQ@Q@@@@QlO@@@@@@@QQQgv4##Q#QNpQB8Q@#uyRba"        
echo "                                  ^@@@@@@@@@@@@QQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@QQQQQQQQ@@@@N4#@@@@@QQQ8QKXN@#QjQ#u@@#wp#l?ci"        
echo "                                   Q@@@@@@@@@@@@@@@@@@@QQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@QQQQQQ@@@K%@@@@@QQQ@@SNWOW@igKa@@@%uKHz,"        
echo "                                   *@@@@@@@@@@@@@@@@@@@@QBQ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Q#Q@Q@#KQ@@@@@@@@6@QD@@Dl%z#@@gQg@Q'"        
echo "                                    Q@@@@@@@@@@QQQ@@@@@@@@@@Q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Q@@Q@Q#b@@@@@@@@B@@N4QKj4oQ@QK@Q#"         
echo "                                    l@@@@@@@@@@@@#g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@W%@@@@@@@Q#@#zq@%Q7zQ@XQQi"         
# figlet -c -t -f Bloody "I'm Busy N' Shit"

